
/*
Implement a Java class representing a "Product" with private fields for name, price, and quantity. Include constructors to initialize these fields and methods to update the quantity and calculate the total price. Ensure proper encapsulation of the fields. 
*/


class Product{

    private String name;
    private Double price;
    private String quantity;

    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }

    public Double getPrice() {
        return price;
    }

    public void setPrice(Double price) {
        this.price = price;
    







        
    }


}

public class ProductClass{
    public static void main(String[] args) {
        
    }
}